spring:
  application:
    name: market-data
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms
      connect-timeout: 2000ms

logging:
  level:
    com.trading.marketdata: INFO
