// frontend/app/portfolio/page.tsx
'use client'
import { useEffect, useState } from 'react'
import PositionCard from '@/components/PositionCard'
import EfficientFrontier from '@/components/EfficientFrontier'
import HelpPanel from '@/components/HelpPanel'
import { api } from '@/lib/api-client'
import { RequireAuth, useUser } from '@/context/UserContext'
import { MockPosition } from '@/lib/mockData'

const PORTFOLIO_HELP = {
  title: 'Portfolio — How it works',
  sections: [
    {
      label: 'Unrealised P&L',
      text: 'Profit and loss are calculated as (current mark price − average entry price) × quantity. Positive is green, negative is red. These are unrealised until you close the position.',
    },
    {
      label: 'Efficient Frontier',
      text: 'The curve below is generated by the Analytics service using a Graham Scan convex hull algorithm on simulated risk/return pairs. Each point on the curve represents an "optimal" portfolio — maximum return for a given level of risk (σ).',
    },
    {
      label: "Welford's Volatility",
      text: "Realised volatility is computed online (streaming) using Welford's single-pass algorithm — no need to store all historical returns. It updates every 2 seconds from market data ticks.",
    },
    {
      label: 'LONG vs SHORT',
      text: "A positive quantity means you own the asset (LONG). A negative quantity means you've sold it short. P&L direction is inverted for shorts.",
    },
  ],
}

function PortfolioContent() {
  const { user } = useUser()
  const [positions, setPositions] = useState<MockPosition[]>([])
  const [pnl, setPnl] = useState<number>(0)

  useEffect(() => {
    if (!user) return
    api.getPositions(user.id).then((data: any) => setPositions(data || []))
    api
      .getPnl(user.id)
      .then((val: any) => setPnl(typeof val === 'number' ? val : 0))
  }, [user])

  const totalPnl = positions.reduce((s, p) => s + (p.unrealizedPnl ?? 0), 0)

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center flex-wrap gap-3">
        <h2 className="text-xl font-bold">Portfolio</h2>
        <div className="flex items-center gap-6 text-sm">
          <span className="text-gray-400">
            Positions: <span className="text-white">{positions.length}</span>
          </span>
          <span
            className={`text-lg font-bold ${totalPnl >= 0 ? 'text-green-400' : 'text-red-400'}`}
          >
            {totalPnl >= 0 ? '+' : ''}₹
            {totalPnl.toLocaleString('en-IN', {
              minimumFractionDigits: 2,
              maximumFractionDigits: 2,
            })}{' '}
            P&L
          </span>
          <HelpPanel
            title={PORTFOLIO_HELP.title}
            sections={PORTFOLIO_HELP.sections}
          />
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4">
        {positions.map((p: any) => (
          <PositionCard key={p.id} position={p} />
        ))}
      </div>

      <EfficientFrontier />
    </div>
  )
}

export default function PortfolioPage() {
  return (
    <RequireAuth>
      <PortfolioContent />
    </RequireAuth>
  )
}
